config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  
  root 'pedidos#new'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pedido.rb
class Pedido < ApplicationRecord
    validates :nome, presence: true
    validates :email, presence: true    
    validates :cor, presence: true    
    validates :quantidade, presence: true     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        #Envio o email
        UserMailer.welcome_email(@pedido).deliver
        
        format.html { redirect_to @pedido, notice: 'Pedido efetuado com sucesso, você receberá um email de confirmação.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: 'Pedido was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:nome, :email, :cor, :quantidade)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minion Store - Reserve já seu Minion</title>
    <meta name="viewport" content= "width=device-width, initial-scale=1.0"> 

    <%= csrf_meta_tags %>
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">    
    
    <!-- Bootstrap core CSS -->
    
    
    <!-- CSS for layout -->
    <%= stylesheet_link_tag "core.css" %>
    <%= stylesheet_link_tag "pages.css" %>
    
    
    <!-- Custom fonts for this template -->
    <link href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" rel="stylesheet">    
    

  </head>

  <body class="container-fluid">
    
  <header class="bg-red small text-center text-white-50">
    <div class="container">
      <div class="logo">Minion Store</div>
    </div>
  </header>
  
  <%= yield %>
  

  <!-- Footer -->
  <footer class="small text-center text-white-50">
    <div class="container">
      Minion Store &copy; <br />
      Avenida Presidente Vargas, 123<br />
      Tel: (21) 9999-9999<br />
      <%= link_to 'Área restrita', pedidos_path %>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <%= javascript_include_tag "jquery.min.js" %>
  <%= javascript_include_tag "bootstrap.bundle.min.js" %>
  <%= javascript_include_tag "pedidos.js" %>
    
  </body>
</html>

app/views/pedidos/_form.html.erb
<%= form_with(model: pedido, local: true, class: "needs-validation was-validated") do |form| %>            
            <div class="modal-header"> 
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> 
                <h4 class="modal-title">Preencha o formulário abaixo para finalizar sua reserva</h4> 
            </div> 
            <div class="modal-body"> 
              <% if pedido.errors.any? %>
                <div class="row"> 
                    <div class="col-md-12">               
                      <div id="error_explanation">
                        <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>
                  
                        <ul>
                        <% pedido.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    </div>
                  </div>
              <% end %>            
                <div class="row"> 
                    <div class="col-md-12"> 
                        <div class="form-group"> 
                            <label for="nome" class="control-label">Nome Completo</label> 
                            <!--<input type="text" class="form-control" id="nome" placeholder="João da Silva">-->
                            <%= form.text_field :nome, id: :pedido_nome, class: "form-control", placeholder: "João da Silva", :required => true %>
                        </div> 
                    </div> 
                </div> 
                <div class="row"> 
                    <div class="col-md-12"> 
                        <div class="form-group"> 
                            <label for="email" class="control-label">Email</label> 
                            <!--<input type="text" class="form-control" id="email" placeholder="joao@teste.com.br"> -->
                            <%= form.email_field :email, id: :pedido_email, class: "form-control", placeholder: "joao@teste.com.br", :required => true %>
                        </div> 
                    </div> 
                </div> 
                <div class="row"> 
                    <div class="col-md-12"> 
                        <div class="form-group"> 
                            <label for="cor" class="control-label">Cor</label> 
                            <!--
                            <select id="cor" class="form-control">
                                <option value="Amarelo">Amarelo</option>
                                <option value="Verde">Verde</option>
                                <option value="Azul">Azul</option>
                            </select>
                            -->
                            <%= form.select :cor, ['Amarelo', 'Verde', 'Azul'], {}, { :class => "form-control", id: "cor" } %>
                        </div> 
                    </div> 
                </div>                 
                <div class="row"> 
                    <div class="col-md-12"> 
                        <div class="form-group"> 
                            <label for="quantidade" class="control-label">Quantidade</label> 
                            <!--<input type="text" class="form-control" id="quantidade"> -->
                            <%= form.number_field :quantidade, id: :pedido_quantidade, min: 1, max: 99, value: 1, class: "form-control", :required => true %>
                        </div> 
                    </div> 
                </div> 
            </div> 
            <div class="modal-footer"> 
                <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Fechar</button> 
                <input type="submit" name="commit" class="btn btn-success waves-effect waves-light" value="Reservar">
            </div> 
<% end %>

app/views/pedidos/edit.html.erb
<h1>Editing Pedido</h1>

<%= render 'form', pedido: @pedido %>

<%= link_to 'Show', @pedido %> |
<%= link_to 'Back', pedidos_path %>

app/views/pedidos/index.html.erb
<div class="row">
   <div class="col-xs-12">
     
       <div class="card-box product-detail-box">
           <div class="row">     
            
              <p id="notice"><%= notice %></p>
              
              
              <h1>Pedidos</h1>
              
              <table class="table table-responsive">
                <thead>
                  <tr>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Cor</th>
                    <th>Quantidade</th>
                    <th></th>
                  </tr>
                </thead>
              
                <tbody>
                  <% @pedidos.each do |pedido| %>
                    <tr>
                      <td><%= pedido.nome %></td>
                      <td><%= pedido.email %></td>
                      <td><%= pedido.cor %></td>
                      <td><%= pedido.quantidade %></td>
                      <td><%= link_to 'Ver', pedido %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              
              <br>
              
              <%= link_to 'Volar ao portal', new_pedido_path %>
          </div>
      </div>
  </div>
</div>

app/views/pedidos/new.html.erb
<div class="row">
   <div class="col-xs-12">
       <div class="card-box product-detail-box">
           <div class="row">
               <div class="col-sm-4">
                   <div class="sp-wrap">
                       <%= image_tag("minion.png", id: "imgPrincipal", width: '318') %>
                   </div>
               </div>

               <div class="col-sm-8">
                   <div class="product-right-info">
                       <h3><b>Boneco de pelúcia minion Stuart</b></h3>
                       <div class="rating">
                            <ul class="list-inline">
                                <li><a class="fa fa-star" href=""></a></li>
                                <li><a class="fa fa-star" href=""></a></li>
                                <li><a class="fa fa-star" href=""></a></li>
                                <li><a class="fa fa-star" href=""></a></li>
                                <li><a class="fa fa-star-o" href=""></a></li>
                            </ul>
                        </div>

                       <h2> <b>R$ 49,99</b><small class="text-muted m-l-10"><del>R$ 59,99</del> </small></b></h2>
                       <hr/>

                        <h5 class="font-600">Cor</h5>
                        <div class="row">
                            <div class="col-sm-1 inline">
                                 <%= image_tag("minion.png", id: "filtroAmarelo", class: "cursorPointer changeColor filtroAmarelo", width: "32") %>
                            </div>
                            <div class="col-sm-1 inline">
                                 <%= image_tag("minion.png", id: "filtroVerde", class: "cursorPointer changeColor filtroVerde", width: "32") %>
                            </div>                        
                            <div class="col-sm-1 inline">
                                 <%= image_tag("minion.png", id: "filtroAzul", class: "cursorPointer changeColor filtroAzul", width: "32") %>
                            </div>
                        </div>

                        <hr />
                        
                       <h5 class="font-600">Descrição</h5>

                       <p class="text-muted">
                            Boneco de Pelucia Minions 30CM<br />
                            O Boneco de Pelúcia Minion Stuart é um verdadeiro sucesso entre as crianças de todas as idades e também entre os adultos. <br />
                            O boneco do Filme Meu Malvado Favorito, é super simpático, macio e fofinho, deixando a brincadeira ainda mais divertida. <br />
                            Possui certificação de segurança do INMETRO proporcionando segurança e diversão garantida para os pequenos.<br />
                            
                            Observe atentamente a idade recomendada para o brinquedo. Pode conter partes pequenas que podem ser engolidas e perigosas.
                       </p>


                       <div class="m-t-30">
                           <button class="btn btn-success waves-effect waves-light" data-toggle="modal" data-target="#con-close-modal" data-animation="slide" data-plugin="custommodal" data-overlaySpeed="200" data-overlayColor="#36404a">
                                <span class="btn-label"><i class="fa fa-shopping-cart"></i></span> Reservar                               
                           </button>

                       </div>
                   </div>
               </div>
           </div>
           <!-- end row -->

           <div class="row m-t-30">
               <div class="col-xs-12">
                   <h4><b>Especificações:</b></h4>
                   <div class="table-responsive m-t-20">
                       <table class="table">
                           <tbody>
                               <tr>
                                   <td width="400">Fabricante</td>
                                   <td>
                                       Estrela
                                   </td>
                               </tr>
                               <tr>
                                   <td>Material</td>
                                   <td>
                                       Pelúcia
                                   </td>
                               </tr>
                               <tr>
                                   <td>Altura</td>
                                   <td>
                                       30cm
                                   </td>
                               </tr>
                               <tr>
                                   <td>Largura</td>
                                   <td>
                                       10cm
                                   </td>
                               </tr>
                               <tr>
                                   <td>Peso</td>
                                   <td>
                                       1.2kg
                                   </td>
                               </tr>
                               <tr>
                                   <td>Modelo:</td>
                                   <td>
                                       ABC2019
                                   </td>
                               </tr>
                               <tr>
                                   <td>Idade recomendada</td>
                                   <td>
                                      A partir de 3 anos
                                   </td>
                               </tr>
                           </tbody>
                       </table>
                   </div>
               </div>
           </div>


       </div> <!-- end card-box/Product detai box -->
       
       
<div id="con-close-modal" class="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog"> 
        <div class="modal-content"> 
            
            <%= render 'form', pedido: @pedido %>

        </div> 
    </div>
</div><!-- /.modal -->          
       
   </div> <!-- end col -->
</div> <!-- end row -->

app/views/pedidos/show.html.erb
<div class="row">
   <div class="col-xs-12">
     
       <div class="card-box product-detail-box">
           <div class="row">     

            <div class="alert alert-success alert-dismissible show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <p id="notice"><%= notice %></p>
            </div>
            
            <p>
              <strong>Nome:</strong>
              <%= @pedido.nome %>
            </p>
            
            <p>
              <strong>Email:</strong>
              <%= @pedido.email %>
            </p>
            
            <p>
              <strong>Cor:</strong>
              <%= @pedido.cor %>
            </p>
            
            <p>
              <strong>Quantidade:</strong>
              <%= @pedido.quantidade %>
            </p>
            
            <%= link_to 'Voltar ao portal', new_pedido_path %>
         </div>
     </div>
     
   </div>
</div>